### ISSUE TITLE
MissingMethodException while running locally

### ISSUE THREAD

**Issue by skbr1234** [RickAndMSFT/Async-ASP.NET#1]
I was trying to learn [asynchronity](http://www.asp.net/mvc/overview/performance/using-asynchronous-methods-in-aspnet-mvc-4#HowRequestsProcessedByTP) and run this project locally. While executing the project **WebAPIpgw** I got this error at start-up:

```
 An exception of type 'System.MissingMethodException' occurred in mscorlib.dll but was not handled in user code

 Additional information: Method not found: 'Void Newtonsoft.Json.Serialization.DefaultContractResolver.set_IgnoreSerializableAttribute(Boolean)'.
```

The error pops up at

```
        // Detailed WebAPI error messages 
        GlobalConfiguration.Configuration.IncludeErrorDetailPolicy = IncludeErrorDetailPolicy.Always; //IncludeErrorDetailPolicy Review
```

Inside `Application_Start` method

**Comment by bedwar2** [comment]
Try switching to an older version of Newtonsoft.json.  It has probably changed in last 3 years.
